spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pear?user=root&password=root&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /pear
